version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pgsql
    container_name: db-postgresql
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
volumes:
  db:
    driver: local